### ISSUE TITLE
Ur LiquidEQ causes segmentation faults

### ISSUE THREAD

**Issue by ra1nst0rm3d** [Audio4Linux/Viper4Linux-GUI#1]
It causes at PaintEvent()

**Comment by timschneeb** [comment]
Could you provide more information about it?

What were you doing before it happened and do you have a stack trace available?

Also, I don't recommend you to use this new version of Viper4Linux-GUI just yet. It is supposed to be used  together with a newer version of Viper4Linux which is not yet fully released. Check out [Viper4Linux-GUI-Legacy](https://github.com/ThePBone/Viper4Linux-GUI-Legacy) instead.

**Comment by ra1nst0rm3d** [comment]
I've build ur latest GUI and I try go to EQ page, it crashes
GDB told that crash causes at PaintEvent()

**Comment by timschneeb** [comment]
Commit fb87e839efcddd00ed4230f3cdd6376b27cab9f0 fixes this issue. For some reason this segfault only occurred in release and not in debug mode.
