### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by RashiqAzhan** [Audio4Linux/Viper4Linux-GUI#11]
Any thoughts or plans to add support for NixOS? Would really appreciate the addition.

**Comment by timschneeb** [comment]
I don't have any plans to maintain packages for NixOS, but you can always install this app by compiling it from sources manually.
Installation instructions can be found here: https://github.com/Audio4Linux/Viper4Linux-GUI#build-from-sources

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/pull/156461
Merged
