### ISSUE TITLE
Crashes!

### ISSUE THREAD

**Issue by ra1nst0rm3d** [Audio4Linux/Viper4Linux-GUI#3]
Maybe you want to make push more STABLE?
I've builded latest V4L-GUI and it crashed!

`Caught SIGSEGV (11) in ???
Fault at memory location 0x45146fc0 due to address not mapped to object (1).
Thread 7043: V4L_Frontend
=== Context:
R8:81ca4014 R9:6 R10:37d66070 R11:6d6f682f R12:45147238 R13:45147240 R14:45147278
R15:0 RDI:45147240 RSI:45147238 RBP:45147238 RBX:81eb7ae0 RDX:0 RAX:2f RCX:0
RSP:45146fb0 RIP:383bb7aa EFL:10202 CSGSFS:33 ERR:6 TRAPNO:e OLDMASK:0 CR2:45146fc0
=== Binary:
Compile date: Mar 30 2020 17:44:53
GNU version: 90300
=== Backtrace:
./V4L_Frontend[8109c000](+7605f)[8111205f]
./V4L_Frontend[8109c000](+769ee)[811129ee]
/usr/lib/libpthread.so.0[3814f000](+14800)[38163800]
/usr/lib/libQt5Core.so.5[381f7000](+1c47aa)[383bb7aa]
/usr/lib/libQt5Core.so.5[381f7000](_ZN4QDir9cleanPathERK7QString+b2)[383bc032]
/usr/lib/libQt5Core.so.5[381f7000](+23f46b)[3843646b]
/usr/lib/libQt5Core.so.5[381f7000](_ZN4QDir8homePathEv+1f)[383b9d5f]
./V4L_Frontend[8109c000](+6cbd2)[81108bd2]
./V4L_Frontend[8109c000](+e13f0)[8117d3f0]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
./V4L_Frontend[8109c000](+e1522)[8117d522]
=== Code:
383bb76a:  00 49 89 c4 e9 9f 30 ed ff 90 66 66 2e 0f 1f 84 00 00 00 00 00 90 e9 db
383bb782:  5a 00 00 66 66 2e 0f 1f 84 00 00 00 00 00 41 57 49 89 cf 41 56 41 55 49
383bb79a:  89 fd 41 54 49 89 f4 55 53 48 81 ec 48 02 00 00>89 54 24 10 64 48 8b 04
383bb7b2:  25 28 00 00 00 48 89 84 24 38 02 00 00 31 c0 48 8b 06 8b 68 04 48 85 c9
383bb7ca:  74 03 c6 01 00 85 ed 75 45 49 89 45 00 8b 10 83 c2 01 83 fa 01 0f 87 a5
383bb7e2:  04 00 00 48 8b 84 24 38
=== Local backtrace:
0x0000000000075b3c: printBacktrace у airbag.c:?
0x0000000000076cc3: sigHandler у airbag.c:?
0x0000000000014800: ?? ??:0
0x00000000001c47aa: ?? ??:0
0x00000000001c5032: ?? ??:0
0x000000000023f46b: ?? ??:0
0x00000000001c2d5f: ?? ??:0
0x000000000006cbd2: AppConfigWrapper::getPath() у appconfigwrapper.cpp:52 (discriminator 3)
0x00000000000e13f0: MainWindow::readConfig() у mainwindow.cpp:1325
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
0x00000000000e1522: MainWindow::readConfig() у mainwindow.cpp:1333 (discriminator 1)
=== System:
Linux version 5.5.10-artix1-1 (linux@artixlinux) (gcc version 9.3.0 (Artix Linux 9.3.0-1)) #1 SMP PREEMPT Wed, 18 Mar 2020 14:01:09 +0000
LSB Version:    1.4
Distributor ID: Artix
Description:    Artix Linux
Release:        rolling
Codename:       n/a
`

**Comment by timschneeb** [comment]
While I can't reproduce your crash, I may have found the error source. 

A fix has been pushed: 2fc6d33

**Comment by ra1nst0rm3d** [comment]
Fixed!
