### ISSUE TITLE
Package problems on Ubuntu/Mint 20

### ISSUE THREAD

**Issue by oguzbakir** [Audio4Linux/Viper4Linux-GUI#4]
Hello, tried to install deb package to Ubuntu/Mint 20 and gstreamer-1.0 package is not found.
![Screenshot from 2020-08-05 23-49-32](https://user-images.githubusercontent.com/23003229/89462674-7529ae00-d776-11ea-9337-6ae4e9cdb672.png)

I can run viper gui app without any problem but missing package is really annoying.

**Comment by timschneeb** [comment]
I've removed that dependency, it was accidentally left over from the arch package.

	sudo apt update
	sudo apt install viper4linux-gui

**Comment by KrutNA** [comment]
Could you fix same problem for deb package?
