### ISSUE TITLE
Make the window resizable

### ISSUE THREAD

**Issue by eviltak** [Audio4Linux/Viper4Linux-GUI#5]
Would it be possible to make the window resizable? The default size is too small for my monitor's DPI. `xprop -remove WM_NORMAL_HINTS` allows me to enlarge the window to a comfortable size where I can see everything.

**Comment by marchingon12** [comment]
I upvote this. The default Breeze theme would work better with a slightly larger window size.

![viper](https://user-images.githubusercontent.com/41235480/95494808-0511f100-098e-11eb-876b-a846441479f9.png)

**Comment by noahbliss** [comment]
I believe @ThePBone mentioned this being a roadmap item. ^_^

**Comment by timschneeb** [comment]
Yep, I'll update this soon. Keep in mind that I don't really support 3rd-party themes because I'm using several custom UI elements that remain unstyled. You'll have a better experience using 'Fusion', 'Phantom', or even 'Windows' rather than themes like 'Breeze'.

**Comment by timschneeb** [comment]
Commit 7b02fc0b29ba1e9ef330eecafdec0fbf02b2eafc fixes this issue.
Arch users can use `yay -S viper4linux-gui-git` to update and Debian users can grab a build here: <https://nightly.timschneeberger.me/vipergui-debian/viper4linux-gui_2.2-build42.deb>

**Comment by kmvan** [comment]
Window too small....
