### ISSUE TITLE
qmake doesn´t generate a makefile from the repo.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Audio4Linux/Viper4Linux-GUI#7]
As simple as that, just display the help text when launched with no options or else.

Can you confirm it isn’t happening on your end?

**Comment by timschneeb** [comment]
I think the syntax for the qmake command changed recently.
You need to explicitly specify the qmake project file now.

This should work: `qmake V4L_Frontend.pro`

**Comment by PoorPocketsMcNewHold** [comment]
Yep. It worked. Thanks for the quick answer.
